### ISSUE TITLE
about datasets 

### ISSUE THREAD

**Issue by houchengbin** [urielsinger/tNodeEmbed#2]
Dear Uriel,

Thank you for your excellent work on dynamic network embedding. 
I'm wondering where can I find the datasets used in your paper, especially Cora and DBLP for node classification.

Chengbin

**Comment by urielsinger** [comment]
Hey Chengbin,

In the [paper](https://www.ijcai.org/proceedings/2019/0640.pdf) you can find on page 5 the links to all datasets.

Uriel

**Comment by houchengbin** [comment]
Hi Uriel,

Thank you for your reply. I've read the experiment setting part. But I'm not sure if I understood it correctly.

In the link prediction task, you split data into training set (80% of the earlier edges to build a graph ) and testing set (20%) according to the edges' timestamps. It seems that, you obtain node embeddings using the 80% data, and then, use the resulting embeddings to predict the 20% edges (possible samples + equal number of non-edges) **all at once**.

In the node classification task, you randomly split the entire dataset into training and testing sets. But it seems that the node classification task is **not that related to the temporal graph...**

Did I misunderstand the experiment settings? Correct me if any. Besides, for node classification task, it is more likely a static network embedding testing framework. How did you use the timestamps on Cora and DBLP datasets?

Chengbin

**Comment by urielsinger** [comment]
Hey Chengbin,

You're right that the node embedding task can be done on a static graph.
The idea is that by using the Temporal information of a node, we might get better results of predicting which class he belongs to.

For example, DBLP, if I once published papers with one group of people and in the last year's I published with another group of people, it might help understand in which field I am, rather then looking on the whole static graph..

Hope this makes it clear.
