### ISSUE TITLE
node2vec missing

### ISSUE THREAD

**Issue by BrisksHan** [urielsinger/tNodeEmbed#5]
Dear author,

I tried to run your code, however, I got the following error:

 from node2vec import Node2Vec
ModuleNotFoundError: No module named 'node2vec'

I have search the repository, it seems the module node2vec is missing in your repository in the current version.

Could you please add this module ?

**Comment by urielsinger** [comment]
It's a requirement of the repo.
Just do `pip install node2vec`

**Comment by BrisksHan** [comment]
Thank you very much !!!

**Comment by BrisksHan** [comment]
Dear author,

Sorry to bother you again, is it possible to get the node embedding of tNodeEmbed at each time step ?

Best regards,

Han

**Comment by urielsinger** [comment]
Unfortunately, tNodeEmbed gives a single embedding at the end of all time steps, as it connects as a layers at the end..

It is possible to do 2 things:
1. Change the test_size and by that moving the pivot_time_step to different end points.
2. Out of the paper scope, but: Create an unsupervised many-to-many architecture that tries to predict the next time-step given all the previous time-steps.

**Comment by BrisksHan** [comment]
Dear author,

Do you consider the Concatenate layer as node embedding ?

**Comment by urielsinger** [comment]
The concat layer is a concat of the nodes embeddings (representing a true/false edge)

**Comment by BrisksHan** [comment]
then, which layer do you consider the final node embedding ? Thank you

**Comment by BrisksHan** [comment]
then, which layer do you consider the final node embedding ? Thank you

**Comment by urielsinger** [comment]
The output of the lstm layer is considered the node embedding.
It depends which task are you trying to do - link prediction or node classification as different tasks have different architectures -> different learned embeddings as it is a supervised layer.

**Comment by BrisksHan** [comment]
I am more interested in link prediction 

In this part of the code
lmda_lyr1 = Lambda(lambda x: x[:, 0, :, :], output_shape=input_shape[1:])(inputs)
lmda_lyr2 = Lambda(lambda x: x[:, 1, :, :], output_shape=input_shape[1:])(inputs
lstm_lyr = LSTM(latent_dim, return_sequences=False, activation='relu')
lstm_lyr1 = lstm_lyr(lmda_lyr1)
lstm_lyr2 = lstm_lyr(lmda_lyr2)


there are two output of LTMS. Then which should I use ?

**Comment by BrisksHan** [comment]
I am more interested in link prediction

In this part of the code
lmda_lyr1 = Lambda(lambda x: x[:, 0, :, :], output_shape=input_shape[1:])(inputs)
lmda_lyr2 = Lambda(lambda x: x[:, 1, :, :], output_shape=input_shape[1:])(inputs
lstm_lyr = LSTM(latent_dim, return_sequences=False, activation='relu')
lstm_lyr1 = lstm_lyr(lmda_lyr1)
lstm_lyr2 = lstm_lyr(lmda_lyr2)

there are two output of LSTM. Then which should I use ?

**Comment by urielsinger** [comment]
Each one is for each node of the respective edge. If you want the embedding of the first node then use the first lstm output, otherwise the second lstm output.

If you prefer using an edge embedding then use the output of the FC after the lstms (fc_lyr1).
