### ISSUE TITLE
The process becomes very slow when it comes to 79% time steps. Move it to GPU?

### ISSUE THREAD

**Issue by ZihanChen1995** [urielsinger/tNodeEmbed#9]
Hi Uriel, 

Thank you so much for the great paper. I am trying to run the model on my computer with the same environment as you wrote in the `requirments.txt`. The model is running well. But when the `Time Steps` comes to 79%, the whole process slows down and becomes very time-consuming. May I ask is there any way that we can figure it out?

<img width="1238" alt="Screen Shot 2021-03-16 at 11 00 57 PM" src="https://user-images.githubusercontent.com/36064256/111408421-a9b9fc80-86ab-11eb-8a1d-dd66503c4b78.png">

---

And when the `Time Steps` comes to 92%, the process shows the "memory leak warning".

<img width="1247" alt="Screen Shot 2021-03-16 at 11 37 29 PM" src="https://user-images.githubusercontent.com/36064256/111411337-bd1b9680-86b0-11eb-902a-645d8da2f6fa.png">

---

1. I am using the `Keras` from the latest `Tensorflow (version 2.3.1)`, as `tensorflow.keras`. So normally speaking it should use GPU automatically. However, the GPU status shows that the whole program is running on CPU only.
2. Is there any explanation that why the program becomes slower in the later stage? Would you mind giving me some hints so I can work on it? 

Thank you so much in advance!

**Comment by urielsinger** [comment]
This is the node2vec initialization, before the keras model started learning.
The larger the step, the larger the graph and therefore slower to run node2vec over it.
You have two options: use a smaller graph or get better hardware to run on.

**Comment by ZihanChen1995** [comment]
I see. I will check the node2vec library for further usage. Thank you for your reply!
